django_projects/P1908345HW1/P1908345HW1/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('', include('library.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('library/', include('library.urls')),

]

django_projects/P1908345HW1/accounts/urls.py
# accounts/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

django_projects/P1908345HW1/library/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.HomePageView.as_view(), name='home'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('book/<slug:slug>-<int:pk>/', views.BookDetailView.as_view(), name='book_detail'),
    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author_detail'),
    path('myBooks/', views.BookListMyView.as_view(), name='book_mylist'),
    path('book/new/', views.BookCreateView.as_view(), name='book_new'),
    path('allBorrowedbooks', views.BookBorrowedList.as_view(), name="borrowed_book"),
    path('search-form/', views.search_form,name='search_form'),
    path('search/', views.search, name='search'),
    path('changeBookStatus/<int:book_id>', views.changeStatus, name="status"),
    path('book/<int:pk>/result', views.ResultsView.as_view(), name="results"),
]

django_projects/P1908345HW1/accounts/models.py
from django.db import models

# Create your models here.

django_projects/P1908345HW1/library/models.py
import uuid
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify


# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=300)
    author = models.ForeignKey('Author', on_delete=models.PROTECT)
    summary = models.CharField(max_length=500)
    ISBN = models.CharField(max_length=100)
    slug = models.SlugField(max_length = 250, null = True, blank = True, allow_unicode=True)

    def __str__(self):
        return self.title
    def save(self, *args, **kwargs):
       self.slug = slugify(self.title)
       super(Book, self).save(*args, **kwargs)
    def get_absolute_url(self):
        return reverse('book_detail', args=[self.slug, self.id])






class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField(null=True, blank=True)

    def __str__(self):
        name = self.first_name + ' ' + self.last_name
        return name

class BookCopies(models.Model):
    """Model representing a specific copy of a book"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this book across whole library')
    book = models.ForeignKey('Book', on_delete=models.PROTECT)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
        )
    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
        )
    class Meta:
        ordering = ['due_back']

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'

django_projects/P1908345HW1/accounts/views.py
# accounts /views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

django_projects/P1908345HW1/library/views.py
from django.views.generic import TemplateView, ListView, DetailView
from .models import Book, Author, BookCopies
from . import models
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse



class HomePageView(TemplateView):
    template_name = 'home.html'
class BookListView(ListView):
    model = Book
    template_name = 'books.html'
    context_object_name = 'library_BookList'

    def get_context_data(self, **kwargs):
        #Call the base implementation first to get the context
        context = super().get_context_data(**kwargs)
        #Create any data add it to the context
        context['section']='dashboard'
        return context
class AuthorListView(ListView):
    model = Author
    template_name = 'authors.html'
    context_object_name = 'library_AuthorList'
class BookDetailView(LoginRequiredMixin, DetailView):
    model = Book
    template_name = 'book_detail.html'
class AuthorDetailView(DetailView):
    model = Author
    template_name = 'author_detail.html'
class BookListMyView(LoginRequiredMixin, ListView):
    template_name='bookcopies_list.html'
    paginate_by = 2
    def get_queryset(self):
        return models.BookCopies.objects.filter(borrower=self.request.user)

    def get_context_data(self, **kwargs):
        #Call the base implementation first to get the context
        context = super().get_context_data(**kwargs)
        #Create any data add it to the context
        context['section']='myBooks'
        return context

class BookCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'library.add_book'
    model = models.Book
    template_name = 'book_new.html'
    fields = ['title','author','summary','ISBN']

    def get_context_data(self, **kwargs):
        #Call the base implementation first to get the context
        context = super().get_context_data(**kwargs)
        #Create any data add it to the context
        context['section']='newBooks'
        return context

class BookBorrowedList(PermissionRequiredMixin, ListView):
    template_name='bookcopies_list.html'
    permission_required = 'library.add_book'
    paginate_by = 2
    def get_queryset(self):
        return models.BookCopies.objects.filter(status="o")

    def get_context_data(self, **kwargs):
        #Call the base implementation first to get the context
        context = super().get_context_data(**kwargs)
        #Create any data add it to the context
        context['section']='borrowedBooks'
        return context


def search_form(request):
    return render(request, 'search_form.html')

def search(request):
    error = False
    # print("DEBUG: SEARCH")
    if 'q' in request.GET and request.GET['q']:
        q = request.GET['q']
        if not q:
            error = True
        else:
            books = Book.objects.filter(title__icontains=q)
            return render(request, 'search_results.html', {'books': books, 'query': q})
    return render (request, 'search_form.html', {'error': error})

def changeStatus(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    try:
        selected_bookcopy=book.bookcopies_set.get(pk=request.POST['choice'])
    except(KeyError, BookCopies.DoesNotExist):
        return render(request, 'book_detail.html', {
            'book': book,
            'error_message': "You didn't select a bookcopy.",})
    else:
        selected_bookcopy.status = 'o'
        selected_bookcopy.borrower=request.user
        selected_bookcopy.save()
        return HttpResponseRedirect(reverse('results', args=(book.id,)))

class ResultsView(DetailView):
    model = Book
    template_name = 'results.html'

django_projects/P1908345HW1/templates/author_detail.html
<!--templates/author_detail.html-->
{% extends 'base.html' %}
{% block content %}
<h2>{{author.first_name}} {{author.last_name}}</h2>
<p>Date of birth: {{author.date_of_birth}}</p>
<p>Date of death: {{author.date_of_death}}</p>
<p>Books:
<ul>
    {% for book in author.book_set.all %}
    <li>{{book.title}}</li>
    {% endfor %}
</ul>
</p>
{% endblock content %}

django_projects/P1908345HW1/templates/authors.html
{% extends 'base.html' %}
{% block content %}
<h1>Authors</h1>
<ul>
    {% for author in library_AuthorList %}
    <li><a href="{% url 'author_detail' author.pk %}">{{author.first_name}} {{author.last_name}}</a></li>
    {% empty %}
    <p>There is no author in our library.</p>
    {% endfor %}
</ul>
{% endblock content %}

django_projects/P1908345HW1/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        {% block title %}<title>P1908345 Library</title>{% endblock %}
        <link href="{% static "css/base.css" %}" rel="stylesheet">
        <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
        <meta http-equiv="Pragma" content="no-cache" />
        <meta http-equiv="Expires" content="0" />
    </head>
    <body>
        <div id="header">
            <span class="logo">Library</span>
            {% if request.user.is_authenticated %}
            <ul class="menu">
                <li {% if section == "dashboard" %}class="selected"{% endif %}>
                    <a href="{% url 'books' %}">All Books</a>
                </li>
                <li {% if section == "myBooks" %}class="selected"{% endif %}>
                    <a href="{% url 'book_mylist' %}">My Books</a>
                </li>
                {% if perms.library.add_book %}
                <li {% if section == "newBooks" %}class="selected"{% endif %}>
                    <a href="{% url 'book_new' %}">New Books</a>
                </li>
                <li {% if section == "borrowedBooks" %}class="selected"{% endif %}>
                    <a href="{% url 'borrowed_book' %}">All Borrowed Books</a>
                </li>
                {% endif %}
            </ul>
            {% endif %}
            <span class="user">
            {% if request.user.is_authenticated %}
                Hello {{ user.username }},
                <a href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a href="{% url 'login' %}">Login</a>
            {% endif %}
            </span>
        </div>
        {% block sidebar %}
        <ul class='sidebar-nav'>
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'books' %}">All books</a></li>
            <li><a href="{% url 'authors' %}">All authors</a></li>
        </ul>
        {% endblock %}
        {% block content %}
        {% endblock content %}
    </body>
</html>

django_projects/P1908345HW1/templates/book_detail.html
<!--templates/book_detail.html-->
{% extends 'base.html' %}
{% block content %}
<h2>{{book.title}}</h2>
<p>Author: {{book.author}}</p>
<p>Summary: {{book.summary}}</p>
<p>ISBN: {{book.ISBN}}</p>
<p>We have the following book copies. (For the status: we have 'm' for 'Maintenance', 'o' for 'On loan', 'a' for 'Available', 'r' for 'Reserved')</p>
<form action="{% url 'status' book.pk %}" method="post">{% csrf_token %}
    {% for choice in book.bookcopies_set.all %}
    {% if choice.status != 'a' %}
    <p>ID: {{choice.id}}    Status: {{choice.status}}</p>
    {% else %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label id="choice{{ forloop.counter }}">ID: {{choice.id}}</label>
    <input type="submit" value="Confirm">
    <br>
    {% endif %}
    {% endfor %}

</form>

{% endblock content %}

django_projects/P1908345HW1/templates/book_new.html
<!--templates/book_new.html-->
{% extends 'base.html' %}
{% block content %}
<h1>New Book</h1>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save"/>
</form>
{% endblock %}

django_projects/P1908345HW1/templates/bookcopies_list.html
<!--templates/bookcopies_list.html-->
{% extends 'base.html' %}
{% block title %}<title>BookCopies</title>{% endblock %}

{% block content %}
{% for bookcopy in object_list %}
    <div>
        <a href= "{% url 'book_detail' slug=bookcopy.book.slug pk=bookcopy.book.pk %}">{{bookcopy.book}}</a>
    </div>
{% empty %}
    <p>There is no borrowed books.</p>
{% endfor %}
<div>
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo;first</a>
    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}
    {% for page in page_obj.paginator.page_range %}
        {% if page == page_obj.number %}
            {{page}}
        {% else %}
        <a href="?page={{page}}">{{page}}</a>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">next</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">last&raquo;</a>
    {% endif %}
</div>
{% endblock content %}

django_projects/P1908345HW1/templates/books.html
{% extends 'base.html' %}
{% block content %}
<h1>Books</h1>
<ul>
    {% for book in library_BookList %}
    {% if request.user.is_authenticated %}
        <li><a href="{% url 'book_detail' slug=book.slug pk=book.pk %}">{{book.title}}</a></li>
    {% else %}
        <li>{{book.title}}</li>
    {% endif %}
    {% empty %}
    <p>There is no book in our library.</p>
    {% endfor %}
</ul>
{% endblock content %}

django_projects/P1908345HW1/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>Welcome to the library</h1>
{% endblock content %}

django_projects/P1908345HW1/templates/results.html
<!--templates/results.html-->
{% extends 'base.html' %}
{% block content %}
<h2>{{book.title}}</h2>
<p>Author: {{book.author}}</p>
<p>Summary: {{book.summary}}</p>
<p>ISBN: {{book.ISBN}}</p>
<p>We have the following book copies. (For the status: we have 'm' for 'Maintenance', 'o' for 'On loan', 'a' for 'Available', 'r' for 'Reserved')</p>
<ul>
    {% for bookcopy in book.bookcopies_set.all %}
    <li>ID: {{bookcopy.id}} Status: {{bookcopy.status}}</li>
    {% endfor %}
</ul>
{% endblock content %}

django_projects/P1908345HW1/templates/search_form.html
<!--templates/search_form.html-->
<html>
    <head>
        <title>Search</title>
    </head>
    <body>
        {% if error %}
        <p style="color: red;">Please submit a search term</p>
        {% endif %}
        <form action="/search/" method="get">
            <input type="text" name="q">
            <input type="submit" value="Search">
        </form>
    </body>
</html>

django_projects/P1908345HW1/templates/search_results.html
<!--templates/search_results.html-->
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8" />
        <title>Book Search</title>
    </head>
    <body>
        <p>You searched for: <strong>{{ query }}</strong></p>
        {% if books %}
        <p>Found {{ books|length }}
        book{{ books|pluralize }}.</p>
        <ul>
            {% for book in books %}
            <li><a href="{% url 'book_detail' slug=book.slug pk=book.pk %}">{{book.title}}</a></li>
            {% endfor %}
        </ul>
        {% else %}
            <p>No books matched your search criteria.</p>
        {% endif %}
    </body>
</html>

django_projects/P1908345HW1/templates/signup.html
<!-- templates/signup.html -->
{% extends 'base.html' %}
{% block content %}
<h1> Sign up </h1>
<form method="post">{% csrf_token %}
    {{form.as_p}}
    <button type="submit">Sign up</button>
</form>
{% endblock content %}